image:
  repository: helionys/hugomeet
  pullPolicy: IfNotPresent
  tag: latest
manifestManager:
  enabled: true
workload:
  main:
    replicas: 2
    strategy: RollingUpdate
    podSpec:
      containers:
        main:
          args: []

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    privileged: true
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000
        protocol: http
  signaling:
    ports:
      signaling:
        port: 8045
        targetPort: 8045
        protocol: tcp

portal:
  open:
    enabled: true
    path: /
