image:
  repository: helionys/hugomeet
  pullPolicy: IfNotPresent
  tag: latest

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    privileged: true
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

  second:
  enabled: true
    ports:
      second:
        port: 8045
        targetPort: 8045

configmap:
  init:
    enabled: true
    data:
      http.default: |-
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            {{- if hasKey .Values "ixChartContext" }}
            - {{ .Values.ixChartContext.kubernetes_config.cluster_cidr }}
            {{- else }}
              {{- range .Values.hugomeet.trusted_proxies }}
            - {{ . }}
              {{- end }}
            {{- end }}

portal:
  open:
    enabled: true
