apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.14.2
deprecated: false
description: "Traefik is a flexible reverse proxy and Ingress Provider."
icon: https://truecharts.org/img/hotlink-ok/chart-icons/traefik.png
keywords:
  - traefik
  - ingress
kubeVersion: ">=1.16.0-0"
name: traefik
sources:
  - https://github.com/truecharts/charts/tree/master/charts/enterprise/traefik
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
  - https://traefik.io/
type: application
version: 18.0.16
annotations:
  truecharts.org/catagories: |
    - network
