image:
  pullPolicy: IfNotPresent
  repository: didstopia/rust-server
  tag: latest

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  SERVER_DISCRIPTION: Simple Unraid Rust Docker Server
  SERVER_NAME: RustDockerServer

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    ports:
      main:
        port: 28015
        protocol: UDP
        targetPort: 28015

persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd

portal:
  enabled: true
