image:
  pullPolicy: IfNotPresent
  repository: didstopia/rust-server
  tag: latest

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  SERVER_DISCRIPTION: Simple Unraid Rust Docker Server
  SERVER_NAME: RustDockerServer

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    ports:
      main:
        port: 28015
        protocol: UDP
        targetPort: 28015
      rconport:
        enable: true
        ports:
          rconport:
            enable: true
            port: 28016
            protocol: UDP
            targetPort: 28016
      appPort:
        enable: true
        ports:
          appPort:
            enable: true
            port: 28082
            protocol: UDP
            targetPort: 28082

persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd