image:
  pullPolicy: IfNotPresent
  repository: didstopia/rust-server
  tag: latest
  
env:
GAME_PARAMS:

service:
  main:
    ports:
      main:
        port: 28015
        protocol: UDP
        targetPort: 28015
      rconport:
        enable: true
        ports:
          rconport:
            enable: true
            port: 28016
            protocol: TCP
            targetPort: 28016
      appPort:
        enable: true
        ports:
          appPort:
            enable: true
            port: 28082
            protocol: BOTH
            targetPort: 28082
