image:
  pullPolicy: IfNotPresent
  repository: didstopia/rust-server
  tag: latest

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

secretEnv:
  USERNAME: ""
  PASSWRD: ""

env:
  GAME_ID: "258550"
  GAME_PARAMS: +server.maxplayers 10
  GAME_PORT: "28015"
  RCON_WEB: "1"
  RCON_PORT: "28016"
  APP_PORT: "28082"
  OXIDE_MOD: ""
  SERVER_DISCRIPTION: Simple Unraid Rust Docker Server
  SERVER_NAME: RustDockerServer
  VALIDATE: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    ports:
      main:
        port: 28015
        protocol: UDP
        targetPort: 28015
    rconport:
        port: 28016
        protocol: UDP
        targetPort: 28016
    appPort:
        port: 28082
        protocol: UDP
        targetPort: 28082

persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd

portal:
  enabled: true
